### ISSUE TITLE
Compress single image failure

### ISSUE THREAD

**Issue by zhiqiang-zhu** [Justin-Tan/generative-compression#15]
the error as follows：
Traceback (most recent call last):
  File "C:/Users/HP/Desktop/GAN_CC/generative-compression-master/compress.py", line 80, in <module>
    main()
  File "C:/Users/HP/Desktop/GAN_CC/generative-compression-master/compress.py", line 77, in main
    single_compress(config_test, args)
  File "C:/Users/HP/Desktop/GAN_CC/generative-compression-master/compress.py", line 20, in single_compress
    assert (ckpt.model_checkpoint_path), 'Missing checkpoint file!'
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

**Comment by Justin-Tan** [comment]
Have you downloaded the pretrained model? If so, which one?

**Comment by zhiqiang-zhu** [comment]
I don't download  the pretrained model, and which model I should download?

**Comment by Justin-Tan** [comment]
See the readme, I recommend using the one with noise sampling for now
