### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'samples/cityscapes/gan_compr ...  on.pdf'

### ISSUE THREAD

**Issue by onshad** [Justin-Tan/generative-compression#20]
here is error message,  i don't know how to find the file for the program

...
Epoch 0 | Generator Loss: 68.616 | Discriminator Loss: 7.002 | Rate: 0 examples/s (29.01 s) [*]
Epoch 0 | Generator Loss: 30.700 | Discriminator Loss: 1.290 | Rate: 1 examples/s (242.19 s) [*]
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    main()
  File "train.py", line 116, in main
    train(config_train, args)
  File "train.py", line 85, in train
    Utils.single_plot(epoch, step, sess, gan, train_handle, args.name, config)
  File "/home/wujun/generative-compression/utils.py", line 134, in single_plot
    global_step, imtype), format='pdf', dpi=720, bbox_inches='tight', pad_inches=0)
  File "/home/wujun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/figure.py", line 2062, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/wujun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2263, in print_figure
    **kwargs)
  File "/home/wujun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 2578, in print_pdf
    file = PdfFile(filename, metadata=kwargs.pop("metadata", None))
  File "/home/wujun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/backends/backend_pdf.py", line 438, in __init__
    fh, opened = cbook.to_filehandle(filename, "wb", return_opened=True)
  File "/home/wujun/anaconda3/envs/tensorflow/lib/python3.6/site-packages/matplotlib/cbook/__init__.py", line 611, in to_filehandle
    fh = io.open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'samples/cityscapes/gan_compression_my_network_epoch0_step256_gen_comparison.pdf'

**Comment by Justin-Tan** [comment]
Whoops, thought I fixed this - just make a directory called cityscapes in the samples directory.

If you are in the main git area, run `mkdir samples/cityscapes`

**Comment by onshad** [comment]
Thank you so much !!!  The problem solved after _mkdir_
