### ISSUE TITLE
training problem

### ISSUE THREAD

**Issue by tuqiangwang** [Justin-Tan/generative-compression#26]
Training on dataset ADE20k
Building computational graph ...
Training on ADE20k
Training on ADE20k
<------------ Building global image generator architecture ------------>
Sampling noise...
Traceback (most recent call last):
  File "/home/tq/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1567, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 2 in both shapes must be equal, but are 32 and 64. Shapes are [?,?,32] and [?,32,64]. for 'generator/concat' (op: 'ConcatV2') with input shapes: [?,?,32,8], [?,32,64,8], [] and with computed input tensors: input[2] = <-1>.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 119, in <module>
    main()
  File "train.py", line 116, in main
    train(config_train, args)
  File "train.py", line 34, in train
    gan = Model(config, paths, name=args.name, dataset=args.dataset)
  File "/home/tq/generative-compression-master/model.py", line 77, in __init__
    self.z = tf.concat([self.w_hat, Gv], axis=-1)
  File "/home/tq/.local/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1189, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/home/tq/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 953, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/home/tq/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/tq/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/home/tq/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1734, in __init__
    control_input_ops)
  File "/home/tq/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimension 2 in both shapes must be equal, but are 32 and 64. Shapes are [?,?,32] and [?,32,64]. for 'generator/concat' (op: 'ConcatV2') with input shapes: [?,?,32,8], [?,32,64,8], [] and with computed input tensors: input[2] = <-1>.

what can i do ?

**Comment by SusmithBarigidad** [comment]
I am receiving the same error? Any leads
